vscode:
  extensions:
    - davidhouchin.whitespace-plus@0.0.5:uFH6r3ulysOo5SAjDF/3Mw==
    - kylepaulsen.stretchy-spaces@0.0.3:DV0kv6ookiSQvNbQUTsUVg==
    - johnnywong.vscode-ts-whitespace-converter@1.2.1:NOUfbgz61+Hh7sau91IEPQ==